### ISSUE TITLE
Example page doesn't work at all in IE

### ISSUE THREAD

**Issue by antoninadert** [jaredreich/pell#116]
Your example page on https://jaredreich.com/pell
doesn't work with IE at all. 

This is displayed like that: 
![image](https://user-images.githubusercontent.com/8929314/38371834-bac5c7fc-38ed-11e8-9228-8faad8a09258.png)
Below is the list of errors I got on IE:

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: pell
HTML1300: Navigation occurred.
File: pell
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: pell
HTML1300: Navigation occurred.
File: pell
CSS3111: @font-face encountered unknown error.
File: roboto-mono-bold.eot
CSS3111: @font-face encountered unknown error.
File: roboto-mono.eot
[nuxt.js] Cannot load components ReferenceError: 'Promise' is undefined
   "[nuxt.js] Cannot load components"
   {
      [functions]: ,
      __proto__: { },
      description: "'Promise' is undefined",
      message: "'Promise' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'Promise' is undefined
   at n.e (https://jaredreich.com/_nuxt/manifest.cab04e65e6b674718f8b.js:1:628)
   at A (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:115639)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113717)
   at C (https://jaredreich.com/_nuxt/vendor.bundle.73c3499fe0c6a2d25537.js:16:43485)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113525)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:102893)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:102852)
   at A (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:102785)
   at q (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113478)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113879)"
   }

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: pell
HTML1300: Navigation occurred.
File: pell
CSS3111: @font-face encountered unknown error.
File: roboto-mono-bold.eot
CSS3111: @font-face encountered unknown error.
File: roboto-mono.eot
[nuxt.js] Cannot load components ReferenceError: 'Promise' is undefined
   "[nuxt.js] Cannot load components"
   {
      [functions]: ,
      __proto__: { },
      description: "'Promise' is undefined",
      message: "'Promise' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'Promise' is undefined
   at n.e (https://jaredreich.com/_nuxt/manifest.cab04e65e6b674718f8b.js:1:628)
   at A (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:115639)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113717)
   at C (https://jaredreich.com/_nuxt/vendor.bundle.73c3499fe0c6a2d25537.js:16:43485)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113525)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:102893)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:102852)
   at A (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:102785)
   at q (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113478)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113879)"
   }
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: pell
HTML1300: Navigation occurred.
File: pell
CSS3111: @font-face encountered unknown error.
File: roboto-mono-bold.eot
CSS3111: @font-face encountered unknown error.
File: roboto-mono.eot
[nuxt.js] Cannot load components ReferenceError: 'Promise' is undefined
   "[nuxt.js] Cannot load components"
   {
      [functions]: ,
      __proto__: { },
      description: "'Promise' is undefined",
      message: "'Promise' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'Promise' is undefined
   at n.e (https://jaredreich.com/_nuxt/manifest.cab04e65e6b674718f8b.js:1:628)
   at A (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:115639)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113717)
   at C (https://jaredreich.com/_nuxt/vendor.bundle.73c3499fe0c6a2d25537.js:16:43485)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113525)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:102893)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:102852)
   at A (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:102785)
   at q (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113478)
   at Anonymous function (https://jaredreich.com/_nuxt/nuxt.bundle.92ffc057163fb8a40757.js:1:113879)"
   }

```

**Comment by mattbag** [comment]
Probably nuxt doesn't add Promise globally? Try the polyfills
